import type { SolveOutcome, Values } from "./types";

/** Read a numeric field, returning NaN when empty or invalid. */
export function num(values: Values, id: string): number {
  const raw = values[id];
  if (raw === undefined || raw.trim() === "") return NaN;
  return Number(raw.replace(/[,\s]/g, ""));
}

export function str(values: Values, id: string): string {
  return (values[id] ?? "").trim();
}

export function fail(error: string): SolveOutcome {
  return { ok: false, error };
}

/** Round to a sensible number of decimal places without trailing zeros. */
export function fmt(value: number, dp = 4): string {
  if (!Number.isFinite(value)) return "—";
  const rounded = Number(value.toFixed(dp));
  return String(rounded);
}

/** Significant-figures formatting, used where exam answers are quoted to 3 s.f. */
export function sf(value: number, figures = 3): string {
  if (!Number.isFinite(value)) return "—";
  if (value === 0) return "0";
  const digits = Math.ceil(Math.log10(Math.abs(value)));
  const power = figures - digits;
  const magnitude = Math.pow(10, power);
  const rounded = Math.round(value * magnitude) / magnitude;
  return String(rounded);
}

export function gcd(a: number, b: number): number {
  let x = Math.abs(a);
  let y = Math.abs(b);
  while (y) {
    const t = y;
    y = x % y;
    x = t;
  }
  return x || 1;
}

export function lcm(a: number, b: number): number {
  return Math.abs(a * b) / gcd(a, b);
}

/**
 * Convert a decimal to the simplest fraction using continued fractions, so
 * probability and ratio answers can be shown as fractions rather than long
 * decimals.
 */
export function toFraction(value: number, maxDenominator = 10000): string {
  if (!Number.isFinite(value)) return "—";
  if (Number.isInteger(value)) return String(value);

  const sign = value < 0 ? "-" : "";
  const x = Math.abs(value);
  let h1 = 1;
  let h0 = 0;
  let k1 = 0;
  let k0 = 1;
  let b = x;

  do {
    const a = Math.floor(b);
    let h2 = a * h1 + h0;
    let k2 = a * k1 + k0;
    if (k2 > maxDenominator) break;
    h0 = h1;
    h1 = h2;
    k0 = k1;
    k1 = k2;
    b = 1 / (b - a);
  } while (Math.abs(x - h1 / k1) > 1e-12);

  if (k1 === 1) return `${sign}${h1}`;
  return `${sign}${h1}/${k1}`;
}

/** Turn a decimal into a mixed number, e.g. 7/4 -> "1 3/4". */
export function toMixedFraction(value: number, maxDenominator = 10000): string {
  const fraction = toFraction(value, maxDenominator);
  const [numeratorRaw, denominatorRaw] = fraction.split("/");
  if (!denominatorRaw) return fraction;
  const numerator = Number(numeratorRaw);
  const denominator = Number(denominatorRaw);
  const whole = Math.trunc(numerator / denominator);
  const remainder = Math.abs(numerator % denominator);
  if (whole === 0) return `${numerator}/${denominator}`;
  if (remainder === 0) return String(whole);
  return `${whole} ${remainder}/${denominator}`;
}

/** Deterministic PRNG so a worksheet or quiz can be regenerated by seed. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function randInt(rng: () => number, min: number, max: number): number {
  return min + Math.floor(rng() * (max - min + 1));
}

export function pick<T>(rng: () => number, items: T[]): T {
  return items[Math.floor(rng() * items.length)];
}

/** Split a comma or space separated list into numbers. */
export function parseNumbers(input: string): number[] {
  return input
    .split(/[,\s]+/)
    .map((part) => part.trim())
    .filter((part) => part.length > 0)
    .map(Number);
}

/** Split a comma separated list into trimmed strings. */
export function parseList(input: string): string[] {
  return input
    .split(",")
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
}

/** True when every field with a default was left untouched (used for auto-run). */
export function hasDefaults(values: Values): boolean {
  return Object.values(values).every((value) => value !== "");
}
